
#Machine Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	enrichmentChamber = "200000000"
	#Base energy storage (Joules).
	osmiumCompressor = "800000000"
	#Base energy storage (Joules).
	combiner = "400000000"
	#Base energy storage (Joules).
	crusher = "200000000"
	#Base energy storage (Joules).
	metallurgicInfuser = "200000000"
	#Base energy storage (Joules).
	purificationChamber = "800000000"
	#Base energy storage (Joules).
	energizedSmelter = "200000000"
	#Base energy storage (Joules).
	digitalMiner = "400000000"
	#Base energy storage (Joules).
	electricPump = "400000000"
	#Base energy storage (Joules).
	chargePad = "5120000000"
	#Base energy storage (Joules).
	rotaryCondensentrator = "200000000"
	#Base energy storage (Joules).
	oxidationChamber = "800000000"
	#Base energy storage (Joules).
	chemicalInfuser = "800000000"
	#Base energy storage (Joules).
	chemicalInjectionChamber = "1600000000"
	#Base energy storage (Joules).
	electrolyticSeparator = "1600000000"
	#Base energy storage (Joules).
	precisionSawmill = "200000000"
	#Base energy storage (Joules).
	chemicalDissolutionChamber = "1600000000"
	#Base energy storage (Joules).
	chemicalWasher = "800000000"
	#Base energy storage (Joules).
	chemicalCrystallizer = "1600000000"
	#Base energy storage (Joules).
	seismicVibrator = "200000000"
	#Base energy storage (Joules).
	pressurizedReactionBase = "20000000"
	#Base energy storage (Joules).
	fluidicPlenisher = "400000000"
	#Base energy storage (Joules).
	laser = "20000000000"
	#Base energy storage (Joules).
	formulaicAssemblicator = "400000000"
	#Base energy storage (Joules).
	teleporter = "50000000000"
	#Base energy storage (Joules).
	modificationStation = "400000000"
	#Base energy storage (Joules).
	isotopicCentrifuge = "800000000"
	#Base energy storage (Joules).
	nutritionalLiquifier = "400000000"
	#Base energy storage (Joules). Also defines max process rate.
	antiprotonicNucleosynthesizer = "10000000000000"
	#Base energy storage (Joules). Also defines max output rate.
	spsPort = "10000000000000"
	#Base energy storage (Joules).
	pigmentExtractor = "40000"
	#Base energy storage (Joules).
	pigmentMixer = "80000"
	#Base energy storage (Joules).
	paintingMachine = "40000"

