
[baublesinterface]
	#Interface corner margins
	#Range: > 0
	interface_margins = 5
	#Corner Position
	#Allowed Values: TOP_LEFT, BOTTOM_LEFT, TOP_RIGHT, BOTTOM_RIGHT
	interface_position = "BOTTOM_LEFT"
	#When enabled, the interface is set to vertical orientation.
	vertical_orientation = true
	#Should this render or not.
	enabled = true

