
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 432330
	#The name of the modpack
	modpackName = "Supernova Empires 4"
	#The version of the modpack
	modpackVersion = "8.0.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

